# Generated by Django 4.0.3 on 2022-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='0711287999', max_length=10),
        ),
    ]
