# Generated by Django 4.0.3 on 2022-03-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0003_alter_profile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(to='restF.project'),
        ),
    ]
