# Generated by Django 4.0.3 on 2022-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.TextField(default='test'),
        ),
    ]
