# Generated by Django 4.0.3 on 2022-03-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0009_review_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
    ]
