# Generated by Django 4.0.3 on 2022-03-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0010_remove_review_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
    ]
