# Generated by Django 4.0.3 on 2022-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restF', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
